# Generated by Django 5.1.7 on 2025-03-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("book_count", models.IntegerField(default=0)),
                ("genre", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("publication_date", models.DateField()),
                ("isbn", models.CharField(max_length=13)),
                ("image", models.ImageField(upload_to="books/")),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["-publication_date"],
            },
        ),
    ]
