# Generated by Django 5.1.7 on 2025-03-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_book_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="image",
        ),
    ]
